In [1]:
text = ''' Natural Language Processing (NLP) is a branch of artificial intelligence that focuses on enabling computers to understand, interpret, and generate human language. It combines concepts from computer science, linguistics, machine learning, and data science to process both written and spoken language. NLP is widely used in applications such as machine translation, chatbots, speech recognition, sentiment analysis, text summarization, spam detection, and question-answering systems.

In today's digital world, enormous amounts of textual data are generated every second through emails, social media platforms, online reviews, blogs, news articles, and customer support conversations. Extracting meaningful information from this unstructured text manually is difficult and time-consuming. NLP techniques automate this process by converting raw text into a structured format that computers can analyze efficiently.

Before applying machine learning algorithms, text usually undergoes a preprocessing stage. Text preprocessing is one of the most important steps in NLP because raw text often contains punctuation marks, numbers, special symbols, HTML tags, emojis, repeated words, and stop words that may not contribute significantly to the analysis. The preprocessing pipeline generally includes converting text to lowercase, removing punctuation, tokenization, stop word removal, stemming or lemmatization, and vectorization.

Tokenization is the process of splitting a document into smaller units called tokens. These tokens may be words, sentences, or even characters depending on the application. For example, the sentence "Python is an amazing programming language." can be tokenized into individual words such as Python, is, an, amazing, programming, and language.

Stop words are commonly used words such as "the", "is", "are", "of", "in", and "to". These words appear frequently in most documents but often carry little meaningful information for many NLP tasks. Removing stop words reduces the size of the vocabulary and improves computational efficiency.

Stemming is the process of reducing words to their root form by removing prefixes or suffixes. For example, the words "playing", "played", and "plays" may all be reduced to "play". However, stemming does not always produce valid English words. Lemmatization, on the other hand, uses vocabulary and grammar rules to convert words into their meaningful dictionary form. For example, "better" becomes "good", and "running" becomes "run".

After preprocessing, the cleaned text is transformed into numerical features using techniques such as Bag of Words, TF-IDF, or Word Embeddings. Machine learning models cannot understand plain text directly, so these numerical representations allow algorithms to identify patterns and relationships between words.

Modern NLP has advanced significantly with the introduction of deep learning models and transformer architectures. Models such as BERT, GPT, RoBERTa, and T5 have achieved remarkable performance on tasks including language translation, document classification, text generation, and question answering. These models learn contextual relationships between words, allowing them to understand the meaning of sentences more accurately than traditional approaches.

Despite these advancements, NLP still faces several challenges. Human language is highly ambiguous, and the same word may have different meanings depending on the context. Sarcasm, idioms, slang, abbreviations, and multilingual content further complicate language understanding. Researchers continue to develop more sophisticated algorithms to improve the accuracy and efficiency of NLP systems.

Natural Language Processing continues to transform industries such as healthcare, education, finance, e-commerce, law, and customer service. As artificial intelligence continues to evolve, NLP will play an increasingly important role in enabling seamless communication between humans and machines.'''

In [2]:
text

' Natural Language Processing (NLP) is a branch of artificial intelligence that focuses on enabling computers to understand, interpret, and generate human language. It combines concepts from computer science, linguistics, machine learning, and data science to process both written and spoken language. NLP is widely used in applications such as machine translation, chatbots, speech recognition, sentiment analysis, text summarization, spam detection, and question-answering systems.\n\nIn today\'s digital world, enormous amounts of textual data are generated every second through emails, social media platforms, online reviews, blogs, news articles, and customer support conversations. Extracting meaningful information from this unstructured text manually is difficult and time-consuming. NLP techniques automate this process by converting raw text into a structured format that computers can analyze efficiently.\n\nBefore applying machine learning algorithms, text usually undergoes a preprocess

**Remove punctuations**

**SENTENCE TOKENIZATION**

In [3]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
from nltk.tokenize import sent_tokenize
sentences = sent_tokenize(text)

In [5]:
sentences

[' Natural Language Processing (NLP) is a branch of artificial intelligence that focuses on enabling computers to understand, interpret, and generate human language.',
 'It combines concepts from computer science, linguistics, machine learning, and data science to process both written and spoken language.',
 'NLP is widely used in applications such as machine translation, chatbots, speech recognition, sentiment analysis, text summarization, spam detection, and question-answering systems.',
 "In today's digital world, enormous amounts of textual data are generated every second through emails, social media platforms, online reviews, blogs, news articles, and customer support conversations.",
 'Extracting meaningful information from this unstructured text manually is difficult and time-consuming.',
 'NLP techniques automate this process by converting raw text into a structured format that computers can analyze efficiently.',
 'Before applying machine learning algorithms, text usually unde

**WORD TOKENIZATION**

In [6]:
from nltk.tokenize import word_tokenize
words=word_tokenize(text)

In [7]:
words

['Natural',
 'Language',
 'Processing',
 '(',
 'NLP',
 ')',
 'is',
 'a',
 'branch',
 'of',
 'artificial',
 'intelligence',
 'that',
 'focuses',
 'on',
 'enabling',
 'computers',
 'to',
 'understand',
 ',',
 'interpret',
 ',',
 'and',
 'generate',
 'human',
 'language',
 '.',
 'It',
 'combines',
 'concepts',
 'from',
 'computer',
 'science',
 ',',
 'linguistics',
 ',',
 'machine',
 'learning',
 ',',
 'and',
 'data',
 'science',
 'to',
 'process',
 'both',
 'written',
 'and',
 'spoken',
 'language',
 '.',
 'NLP',
 'is',
 'widely',
 'used',
 'in',
 'applications',
 'such',
 'as',
 'machine',
 'translation',
 ',',
 'chatbots',
 ',',
 'speech',
 'recognition',
 ',',
 'sentiment',
 'analysis',
 ',',
 'text',
 'summarization',
 ',',
 'spam',
 'detection',
 ',',
 'and',
 'question-answering',
 'systems',
 '.',
 'In',
 'today',
 "'s",
 'digital',
 'world',
 ',',
 'enormous',
 'amounts',
 'of',
 'textual',
 'data',
 'are',
 'generated',
 'every',
 'second',
 'through',
 'emails',
 ',',
 'social'

**LOWER SENTENCES**

In [8]:
lower_sentences = [sentence.lower() for sentence in sentences]

In [9]:
lower_sentences

[' natural language processing (nlp) is a branch of artificial intelligence that focuses on enabling computers to understand, interpret, and generate human language.',
 'it combines concepts from computer science, linguistics, machine learning, and data science to process both written and spoken language.',
 'nlp is widely used in applications such as machine translation, chatbots, speech recognition, sentiment analysis, text summarization, spam detection, and question-answering systems.',
 "in today's digital world, enormous amounts of textual data are generated every second through emails, social media platforms, online reviews, blogs, news articles, and customer support conversations.",
 'extracting meaningful information from this unstructured text manually is difficult and time-consuming.',
 'nlp techniques automate this process by converting raw text into a structured format that computers can analyze efficiently.',
 'before applying machine learning algorithms, text usually unde

**LOWER WORDS**

In [10]:
lower_words = [word.lower() for word in words if word.isalpha()]

In [11]:
lower_words

['natural',
 'language',
 'processing',
 'nlp',
 'is',
 'a',
 'branch',
 'of',
 'artificial',
 'intelligence',
 'that',
 'focuses',
 'on',
 'enabling',
 'computers',
 'to',
 'understand',
 'interpret',
 'and',
 'generate',
 'human',
 'language',
 'it',
 'combines',
 'concepts',
 'from',
 'computer',
 'science',
 'linguistics',
 'machine',
 'learning',
 'and',
 'data',
 'science',
 'to',
 'process',
 'both',
 'written',
 'and',
 'spoken',
 'language',
 'nlp',
 'is',
 'widely',
 'used',
 'in',
 'applications',
 'such',
 'as',
 'machine',
 'translation',
 'chatbots',
 'speech',
 'recognition',
 'sentiment',
 'analysis',
 'text',
 'summarization',
 'spam',
 'detection',
 'and',
 'systems',
 'in',
 'today',
 'digital',
 'world',
 'enormous',
 'amounts',
 'of',
 'textual',
 'data',
 'are',
 'generated',
 'every',
 'second',
 'through',
 'emails',
 'social',
 'media',
 'platforms',
 'online',
 'reviews',
 'blogs',
 'news',
 'articles',
 'and',
 'customer',
 'support',
 'conversations',
 'extr

In [12]:
len(lower_words)

537

**STOP WORDS**

In [13]:
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [14]:
stop_words = set(stopwords.words('english'))

In [15]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [16]:
filtered_words = [word for word in words if word.lower() not in stop_words and word.isalpha()]

In [17]:
len(filtered_words)

361

**STEMMING**

In [18]:
from nltk.stem import PorterStemmer

In [19]:
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_words]
stemmed_words

['natur',
 'languag',
 'process',
 'nlp',
 'branch',
 'artifici',
 'intellig',
 'focus',
 'enabl',
 'comput',
 'understand',
 'interpret',
 'gener',
 'human',
 'languag',
 'combin',
 'concept',
 'comput',
 'scienc',
 'linguist',
 'machin',
 'learn',
 'data',
 'scienc',
 'process',
 'written',
 'spoken',
 'languag',
 'nlp',
 'wide',
 'use',
 'applic',
 'machin',
 'translat',
 'chatbot',
 'speech',
 'recognit',
 'sentiment',
 'analysi',
 'text',
 'summar',
 'spam',
 'detect',
 'system',
 'today',
 'digit',
 'world',
 'enorm',
 'amount',
 'textual',
 'data',
 'gener',
 'everi',
 'second',
 'email',
 'social',
 'media',
 'platform',
 'onlin',
 'review',
 'blog',
 'news',
 'articl',
 'custom',
 'support',
 'convers',
 'extract',
 'meaning',
 'inform',
 'unstructur',
 'text',
 'manual',
 'difficult',
 'nlp',
 'techniqu',
 'autom',
 'process',
 'convert',
 'raw',
 'text',
 'structur',
 'format',
 'comput',
 'analyz',
 'effici',
 'appli',
 'machin',
 'learn',
 'algorithm',
 'text',
 'usual',
 

**LEMMATIZATION**

In [20]:
from nltk.stem import WordNetLemmatizer

In [21]:
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
lemmatized_words

['Natural',
 'Language',
 'Processing',
 'NLP',
 'branch',
 'artificial',
 'intelligence',
 'focus',
 'enabling',
 'computer',
 'understand',
 'interpret',
 'generate',
 'human',
 'language',
 'combine',
 'concept',
 'computer',
 'science',
 'linguistics',
 'machine',
 'learning',
 'data',
 'science',
 'process',
 'written',
 'spoken',
 'language',
 'NLP',
 'widely',
 'used',
 'application',
 'machine',
 'translation',
 'chatbots',
 'speech',
 'recognition',
 'sentiment',
 'analysis',
 'text',
 'summarization',
 'spam',
 'detection',
 'system',
 'today',
 'digital',
 'world',
 'enormous',
 'amount',
 'textual',
 'data',
 'generated',
 'every',
 'second',
 'email',
 'social',
 'medium',
 'platform',
 'online',
 'review',
 'blog',
 'news',
 'article',
 'customer',
 'support',
 'conversation',
 'Extracting',
 'meaningful',
 'information',
 'unstructured',
 'text',
 'manually',
 'difficult',
 'NLP',
 'technique',
 'automate',
 'process',
 'converting',
 'raw',
 'text',
 'structured',
 'for

In [22]:
clean_text = " ".join(lemmatized_words)

print(clean_text)

Natural Language Processing NLP branch artificial intelligence focus enabling computer understand interpret generate human language combine concept computer science linguistics machine learning data science process written spoken language NLP widely used application machine translation chatbots speech recognition sentiment analysis text summarization spam detection system today digital world enormous amount textual data generated every second email social medium platform online review blog news article customer support conversation Extracting meaningful information unstructured text manually difficult NLP technique automate process converting raw text structured format computer analyze efficiently applying machine learning algorithm text usually undergoes preprocessing stage Text preprocessing one important step NLP raw text often contains punctuation mark number special symbol HTML tag emojis repeated word stop word may contribute significantly analysis preprocessing pipeline generall

**PREPROCESSING PART 2**

**1. ONE HOT ENCODING**

In [23]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array(lemmatized_words).reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False)

onehot = encoder.fit_transform(words)

print(onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
print(encoder.categories_)

[array(['BERT', 'Bag', 'Despite', 'Embeddings', 'English', 'Extracting',
       'GPT', 'HTML', 'However', 'Human', 'Language', 'Lemmatization',
       'Machine', 'Models', 'Modern', 'NLP', 'Natural', 'Processing',
       'Python', 'Removing', 'Researchers', 'RoBERTa', 'Sarcasm',
       'Stemming', 'Stop', 'Text', 'Tokenization', 'Word', 'Words',
       'abbreviation', 'accuracy', 'accurately', 'achieved', 'advanced',
       'advancement', 'algorithm', 'allow', 'allowing', 'always',
       'amazing', 'ambiguous', 'amount', 'analysis', 'analyze',
       'answering', 'appear', 'application', 'applying', 'approach',
       'architecture', 'article', 'artificial', 'automate', 'becomes',
       'better', 'blog', 'branch', 'called', 'carry', 'challenge',
       'character', 'chatbots', 'classification', 'cleaned', 'combine',
       'commonly', 'communication', 'complicate', 'computational',
       'computer', 'concept', 'contains', 'content', 'context',
       'contextual', 'continue', 'conti

**2. Bag of Words**

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [clean_text]

vectorizer = CountVectorizer()

bow = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())

print(bow.toarray())

['abbreviation' 'accuracy' 'accurately' 'achieved' 'advanced'
 'advancement' 'algorithm' 'allow' 'allowing' 'always' 'amazing'
 'ambiguous' 'amount' 'analysis' 'analyze' 'answering' 'appear'
 'application' 'applying' 'approach' 'architecture' 'article' 'artificial'
 'automate' 'bag' 'becomes' 'bert' 'better' 'blog' 'branch' 'called'
 'carry' 'challenge' 'character' 'chatbots' 'classification' 'cleaned'
 'combine' 'commonly' 'communication' 'complicate' 'computational'
 'computer' 'concept' 'contains' 'content' 'context' 'contextual'
 'continue' 'continues' 'contribute' 'conversation' 'convert' 'converting'
 'customer' 'data' 'deep' 'depending' 'despite' 'detection' 'develop'
 'dictionary' 'different' 'difficult' 'digital' 'directly' 'document'
 'education' 'efficiency' 'efficiently' 'email' 'embeddings' 'emojis'
 'enabling' 'english' 'enormous' 'even' 'every' 'evolve' 'example'
 'extracting' 'face' 'feature' 'finance' 'focus' 'form' 'format'
 'frequently' 'generally' 'generate' 'genera

**3. N-grams**

In [26]:
from nltk import ngrams
# Unigrams
unigrams = ngrams(filtered_words, 1)
print("Bigrams:", unigrams)
# Bigrams
bigrams = ngrams(filtered_words, 2)
print("Bigrams:", bigrams)

# Trigrams
trigrams = ngrams(filtered_words, 3)
print("Trigrams:", trigrams)

Bigrams: <generator object ngrams at 0x7d2274803840>
Bigrams: <generator object ngrams at 0x7d2274803640>
Trigrams: <generator object ngrams at 0x7d2274803940>


In [27]:
# unigrams
unigrams = list(ngrams(filtered_words, 1))

# bigrams
bigrams = list(ngrams(filtered_words, 2))

# Trigrams
trigrams = list(ngrams(filtered_words, 3))


In [28]:
unigrams

[('Natural',),
 ('Language',),
 ('Processing',),
 ('NLP',),
 ('branch',),
 ('artificial',),
 ('intelligence',),
 ('focuses',),
 ('enabling',),
 ('computers',),
 ('understand',),
 ('interpret',),
 ('generate',),
 ('human',),
 ('language',),
 ('combines',),
 ('concepts',),
 ('computer',),
 ('science',),
 ('linguistics',),
 ('machine',),
 ('learning',),
 ('data',),
 ('science',),
 ('process',),
 ('written',),
 ('spoken',),
 ('language',),
 ('NLP',),
 ('widely',),
 ('used',),
 ('applications',),
 ('machine',),
 ('translation',),
 ('chatbots',),
 ('speech',),
 ('recognition',),
 ('sentiment',),
 ('analysis',),
 ('text',),
 ('summarization',),
 ('spam',),
 ('detection',),
 ('systems',),
 ('today',),
 ('digital',),
 ('world',),
 ('enormous',),
 ('amounts',),
 ('textual',),
 ('data',),
 ('generated',),
 ('every',),
 ('second',),
 ('emails',),
 ('social',),
 ('media',),
 ('platforms',),
 ('online',),
 ('reviews',),
 ('blogs',),
 ('news',),
 ('articles',),
 ('customer',),
 ('support',),
 ('conve

In [29]:
bigrams

[('Natural', 'Language'),
 ('Language', 'Processing'),
 ('Processing', 'NLP'),
 ('NLP', 'branch'),
 ('branch', 'artificial'),
 ('artificial', 'intelligence'),
 ('intelligence', 'focuses'),
 ('focuses', 'enabling'),
 ('enabling', 'computers'),
 ('computers', 'understand'),
 ('understand', 'interpret'),
 ('interpret', 'generate'),
 ('generate', 'human'),
 ('human', 'language'),
 ('language', 'combines'),
 ('combines', 'concepts'),
 ('concepts', 'computer'),
 ('computer', 'science'),
 ('science', 'linguistics'),
 ('linguistics', 'machine'),
 ('machine', 'learning'),
 ('learning', 'data'),
 ('data', 'science'),
 ('science', 'process'),
 ('process', 'written'),
 ('written', 'spoken'),
 ('spoken', 'language'),
 ('language', 'NLP'),
 ('NLP', 'widely'),
 ('widely', 'used'),
 ('used', 'applications'),
 ('applications', 'machine'),
 ('machine', 'translation'),
 ('translation', 'chatbots'),
 ('chatbots', 'speech'),
 ('speech', 'recognition'),
 ('recognition', 'sentiment'),
 ('sentiment', 'analysi

In [30]:
trigrams

[('Natural', 'Language', 'Processing'),
 ('Language', 'Processing', 'NLP'),
 ('Processing', 'NLP', 'branch'),
 ('NLP', 'branch', 'artificial'),
 ('branch', 'artificial', 'intelligence'),
 ('artificial', 'intelligence', 'focuses'),
 ('intelligence', 'focuses', 'enabling'),
 ('focuses', 'enabling', 'computers'),
 ('enabling', 'computers', 'understand'),
 ('computers', 'understand', 'interpret'),
 ('understand', 'interpret', 'generate'),
 ('interpret', 'generate', 'human'),
 ('generate', 'human', 'language'),
 ('human', 'language', 'combines'),
 ('language', 'combines', 'concepts'),
 ('combines', 'concepts', 'computer'),
 ('concepts', 'computer', 'science'),
 ('computer', 'science', 'linguistics'),
 ('science', 'linguistics', 'machine'),
 ('linguistics', 'machine', 'learning'),
 ('machine', 'learning', 'data'),
 ('learning', 'data', 'science'),
 ('data', 'science', 'process'),
 ('science', 'process', 'written'),
 ('process', 'written', 'spoken'),
 ('written', 'spoken', 'language'),
 ('spo

**4. TF-IDF**

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(corpus)

print(tfidf.get_feature_names_out())

print(tfidf_matrix.toarray())

['abbreviation' 'accuracy' 'accurately' 'achieved' 'advanced'
 'advancement' 'algorithm' 'allow' 'allowing' 'always' 'amazing'
 'ambiguous' 'amount' 'analysis' 'analyze' 'answering' 'appear'
 'application' 'applying' 'approach' 'architecture' 'article' 'artificial'
 'automate' 'bag' 'becomes' 'bert' 'better' 'blog' 'branch' 'called'
 'carry' 'challenge' 'character' 'chatbots' 'classification' 'cleaned'
 'combine' 'commonly' 'communication' 'complicate' 'computational'
 'computer' 'concept' 'contains' 'content' 'context' 'contextual'
 'continue' 'continues' 'contribute' 'conversation' 'convert' 'converting'
 'customer' 'data' 'deep' 'depending' 'despite' 'detection' 'develop'
 'dictionary' 'different' 'difficult' 'digital' 'directly' 'document'
 'education' 'efficiency' 'efficiently' 'email' 'embeddings' 'emojis'
 'enabling' 'english' 'enormous' 'even' 'every' 'evolve' 'example'
 'extracting' 'face' 'feature' 'finance' 'focus' 'form' 'format'
 'frequently' 'generally' 'generate' 'genera

**5. Word2Vec**

In [32]:
processed_sentences = []
processed_sentences.append(lemmatized_words)

In [33]:
!pip install gensim

In [34]:
from gensim.models import Word2Vec

model = Word2Vec(
    processed_sentences,
    vector_size=100,
    window=5,
    min_count=1
)

In [35]:
print(model.wv["multilingual"])

[-0.0023007   0.00757217 -0.00308811  0.00353572  0.00018848  0.00143617
 -0.00038853 -0.00846239  0.00879537  0.00697421 -0.00955498 -0.00715972
  0.00213101  0.00025413 -0.00289674  0.00863882 -0.00873761 -0.00294612
  0.0072552  -0.00093976 -0.00547784  0.0089262   0.00669186 -0.00406865
 -0.00733371 -0.00095449  0.00845392 -0.00246615  0.00474355 -0.00184885
  0.00426994 -0.00135337  0.00622029  0.00980615 -0.00840579  0.00617934
 -0.00753411 -0.00928944  0.0055954   0.0021185   0.00543087 -0.00984744
  0.00821524 -0.00844377 -0.0064426   0.00166976 -0.00414776  0.00238889
 -0.00515593 -0.00656323  0.00618564 -0.0019397   0.00659251 -0.00277718
 -0.0008622   0.00413094  0.0069749  -0.00164681 -0.01002054 -0.00227342
  0.00712499  0.0065052  -0.00632269  0.00331914  0.00953385 -0.00782547
  0.00023827  0.0008513  -0.00617685 -0.00543677  0.00529721 -0.00458541
 -0.00490927  0.00219185  0.00951695  0.00737624 -0.00559582 -0.00283714
  0.00904006  0.00052853 -0.00490729 -0.0084099  -0

In [36]:
print(model.wv["text"].shape)

(100,)
